from __future__ import annotations

import argparse
import hashlib
import json
import ntpath
import os
import re
import stat
import sys
from datetime import datetime
from pathlib import Path, PureWindowsPath
from typing import Any, Sequence

_IMPORT_PROJECT_ROOT = Path(
    ntpath.normpath(ntpath.abspath(os.fspath(Path(__file__).parents[2])))
)
if not any(
    ntpath.normcase(entry) == ntpath.normcase(str(_IMPORT_PROJECT_ROOT))
    for entry in sys.path
    if type(entry) is str
):
    sys.path.insert(0, str(_IMPORT_PROJECT_ROOT))

from app.project_root import PROJECT_ROOT as VERIFIED_PROJECT_ROOT
from app.safety.static_audit import (
    _pretty_json_bytes,
    build_inventory_bundle,
    payload_digest,
)


def _verified_inventory_root(_root: Path = VERIFIED_PROJECT_ROOT) -> Path:
    return _root


RUN_ID_PATTERN = re.compile(r"RUN-[A-Z0-9][A-Z0-9-]{5,80}")
REPARSE_ATTRIBUTE = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)


class InventoryPreviewStop(RuntimeError):
    pass


def _absolute_lexical(path: str | os.PathLike[str]) -> Path:
    return Path(ntpath.normpath(ntpath.abspath(os.fspath(path))))


def _same_path(left: Path, right: Path) -> bool:
    return ntpath.normcase(str(left)) == ntpath.normcase(str(right))


def _relative_parts(candidate: Path, root: Path) -> tuple[str, ...] | None:
    candidate_parts = PureWindowsPath(str(candidate)).parts
    root_parts = PureWindowsPath(str(root)).parts
    if len(candidate_parts) < len(root_parts):
        return None
    for actual, expected in zip(candidate_parts, root_parts, strict=False):
        if ntpath.normcase(actual) != ntpath.normcase(expected):
            return None
    return tuple(candidate_parts[len(root_parts) :])


def _verify_existing_chain(path: Path) -> None:
    for component in (*reversed(path.parents), path):
        try:
            identity = os.lstat(component)
        except OSError as exc:
            raise InventoryPreviewStop("required preview path cannot be inspected") from exc
        if (
            stat.S_ISLNK(identity.st_mode)
            or int(getattr(identity, "st_file_attributes", 0)) & REPARSE_ATTRIBUTE
            or int(getattr(identity, "st_reparse_tag", 0))
        ):
            raise InventoryPreviewStop("preview path chain contains a reparse object")
        if stat.S_ISREG(identity.st_mode) and int(identity.st_nlink) != 1:
            raise InventoryPreviewStop("preview path chain contains a hardlinked file")


def _write_exclusive(path: Path, payload: bytes) -> None:
    descriptor = os.open(
        path,
        os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_BINARY", 0),
        0o600,
    )
    try:
        offset = 0
        while offset < len(payload):
            written = os.write(descriptor, payload[offset:])
            if written <= 0:
                raise InventoryPreviewStop("inventory preview write made no progress")
            offset += written
        os.fsync(descriptor)
    finally:
        os.close(descriptor)
    identity = os.lstat(path)
    if not stat.S_ISREG(identity.st_mode) or int(identity.st_nlink) != 1:
        raise InventoryPreviewStop("inventory preview is not a single-link regular file")
    if path.read_bytes() != payload:
        raise InventoryPreviewStop("inventory preview readback differs from generated bytes")


def _validate_timestamp(value: str) -> str:
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError as exc:
        raise InventoryPreviewStop("generated-at must be an ISO-8601 timestamp") from exc
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise InventoryPreviewStop("generated-at must include an explicit timezone")
    now = datetime.now().astimezone()
    age_seconds = (now - parsed.astimezone(now.tzinfo)).total_seconds()
    if age_seconds < -5 or age_seconds > 300:
        raise InventoryPreviewStop(
            "generated-at must be captured from the current clock immediately before generation"
        )
    return value


def _validate_head(value: str) -> str:
    if len(value) != 40 or any(character not in "0123456789abcdef" for character in value):
        raise InventoryPreviewStop("source-head must be a lowercase 40-character Git SHA")
    return value


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build an M0 write-entry inventory in a new Test-local preview only.",
    )
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--generated-at", required=True)
    parser.add_argument("--source-head", required=True)
    return parser.parse_args(argv)


def _summary(
    run_id: str,
    manifest: dict[str, Any],
    manifest_bytes: bytes,
    chunk_bytes: tuple[bytes, ...],
) -> dict[str, Any]:
    return {
        "run_id": run_id,
        "generated_at": manifest["generated_at"],
        "source_head": manifest["source_head"],
        "generator_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "generation_status": "PREVIEW_VERIFIED_NOT_PUBLISHED",
        "source_count": len(manifest["source_manifest"]),
        "entry_count": manifest["entry_count"],
        "chunk_count": len(chunk_bytes),
        "unknown_dynamic_count": manifest["gate"]["unknown_dynamic_count"],
        "unmigrated_count": manifest["gate"]["unmigrated_count"],
        "production_writer_connected": manifest["gate"]["production_writer_connected"],
        "m0_exit_allowed": manifest["gate"]["m0_exit_allowed"],
        "inventory_payload_sha256": payload_digest(manifest),
        "manifest_file_sha256": hashlib.sha256(manifest_bytes).hexdigest(),
        "chunk_files_sha256": [
            hashlib.sha256(payload).hexdigest() for payload in chunk_bytes
        ],
    }


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    if not RUN_ID_PATTERN.fullmatch(args.run_id):
        raise InventoryPreviewStop("run ID contains unsupported syntax")
    generated_at = _validate_timestamp(args.generated_at)
    source_head = _validate_head(args.source_head)
    project_root = _absolute_lexical(Path(__file__).parents[2])
    expected_root = _absolute_lexical(_verified_inventory_root())
    if not _same_path(project_root, expected_root):
        raise InventoryPreviewStop("inventory tool is outside the contracted project root")
    if not _same_path(_absolute_lexical(Path.cwd()), project_root):
        raise InventoryPreviewStop("inventory tool cwd must be the contracted project root")
    expected_python = project_root / ".venv" / "Scripts" / "python.exe"
    if not _same_path(_absolute_lexical(sys.executable), expected_python):
        raise InventoryPreviewStop("inventory tool requires the project virtual environment")
    _verify_existing_chain(project_root)

    preview_parent = project_root / "tmp" / "inventory_preview"
    if not preview_parent.exists():
        os.mkdir(preview_parent)
    _verify_existing_chain(preview_parent)
    preview_root = preview_parent / args.run_id
    if _relative_parts(preview_root, preview_parent) != (args.run_id,):
        raise InventoryPreviewStop("preview root escaped its fixed parent")
    if os.path.lexists(preview_root):
        raise InventoryPreviewStop("inventory preview run already exists")
    os.mkdir(preview_root)
    _verify_existing_chain(preview_root)

    manifest, chunks = build_inventory_bundle(
        generated_at=generated_at,
        source_head=source_head,
    )
    chunk_bytes = tuple(_pretty_json_bytes(chunk) for chunk in chunks)
    manifest_bytes = _pretty_json_bytes(manifest)
    for index, payload in enumerate(chunk_bytes):
        _write_exclusive(preview_root / f"entries-{index:03d}.json", payload)
    _write_exclusive(preview_root / "M0-write-entry-inventory.json", manifest_bytes)
    summary = _summary(args.run_id, manifest, manifest_bytes, chunk_bytes)
    _write_exclusive(preview_root / "preview-summary.json", _pretty_json_bytes(summary))
    print(json.dumps(summary, ensure_ascii=True, sort_keys=True))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except InventoryPreviewStop as exc:
        raise SystemExit(f"INVENTORY_PREVIEW_STOP: {exc}") from None
